Adjust main plugin file to WP Coding Standard
toolstack/gp-auto-extract pull request #3
Opened 2017-01-11 21:28 UTC by brazabr

- Fixed main plugin file to pass validations on: `WordPress-Core`, `WordPress-Extra` and `WordPress-Docs`.

2017-01-11 22:47 UTC, toolstack requested changes
You've used esc_html_e() (and related escaping functions) in places you don't need them and in fact sometimes they would break the display if a translation used some html in them.

2017-01-11 22:47 UTC, toolstack commented on gp-auto-extract.php
> +							<button type="button" class="button cancel alignleft" data-project-id="<? echo esc_attr( $project->id ); ?>"><?php esc_html_e( 'Cancel' ); ?></button>
Can't use a short tag (<?) in the data-project-id attribute.

2017-01-11 22:47 UTC, toolstack commented on gp-auto-extract.php
> +										<option value="<?php echo esc_attr( $id ); ?>" <?php echo selected( $source_type, $id ); ?>><?echo esc_html( $type ); ?></option>;
Can't use a short tag (<?) in the option output attribute.

2017-01-11 22:47 UTC, toolstack commented on gp-auto-extract.php
> +				esc_html__( 'Reset' )
The reset option needs a confirmation alert before executing.

2017-01-11 22:47 UTC, toolstack commented on gp-auto-extract.php
> +										$format_options = array();
Should support auto-detection as the default.

2017-01-11 22:47 UTC, toolstack commented on gp-auto-extract.php
> +	public function before_request() {
This placeholder function was removed in the current tree, you must have added it back in by accident during the rebase.

2017-01-11 22:47 UTC, toolstack commented on gp-auto-extract.php
> +	public function after_request() {
This placeholder function was removed in the current tree, you must have added it back in by accident during the rebase.

2017-01-11 22:47 UTC, toolstack commented on gp-auto-extract.php
> +					$project_settings[ $project->id ]['http_auth_password']  = filter_input( INPUT_POST, 'http_auth_password_' . $project->id );
Storing the password in clear text in the database is a no-no.

2017-01-14 15:42 UTC, brazabr commented on gp-auto-extract.php
> +							<button type="button" class="button cancel alignleft" data-project-id="<? echo esc_attr( $project->id ); ?>"><?php esc_html_e( 'Cancel' ); ?></button>
Typo mistake. Fixed.

2017-01-14 15:42 UTC, brazabr commented on gp-auto-extract.php
> +										<option value="<?php echo esc_attr( $id ); ?>" <?php echo selected( $source_type, $id ); ?>><?echo esc_html( $type ); ?></option>;
Typo mistake. Fixed.

2017-01-14 15:42 UTC, brazabr commented on gp-auto-extract.php
> +										$format_options = array();
Implemented in new commit.

2017-01-14 15:42 UTC, brazabr commented on gp-auto-extract.php
> +	public function after_request() {
Removed in recent commits.

2017-01-14 15:43 UTC, brazabr commented on gp-auto-extract.php
> +	public function before_request() {
Removed in recent commits.

2017-01-15 19:20 UTC, toolstack approved these changes

2017-01-15 19:20 UTC, merged